# Generated by Django 5.0.1 on 2026-01-22 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único da petição",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título da petição (máx. 200 caracteres)",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL amigável (gerado automaticamente)",
                        max_length=220,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição completa da causa (máx. 10.000 caracteres)",
                        max_length=10000,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "signature_goal",
                    models.PositiveIntegerField(
                        help_text="Número de assinaturas desejadas (10 a 1.000.000)",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="Meta de assinaturas",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Data limite para coleta de assinaturas (opcional)",
                        null=True,
                        verbose_name="Prazo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativa"),
                            ("completed", "Concluída"),
                            ("expired", "Expirada"),
                            ("closed", "Fechada"),
                            ("flagged", "Sinalizada"),
                        ],
                        default="active",
                        help_text="Status atual da petição",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se a petição está aceitando assinaturas",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL do PDF original da petição",
                        max_length=500,
                        verbose_name="URL do PDF",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash do conteúdo da petição para verificação",
                        max_length=64,
                        verbose_name="Hash do conteúdo",
                    ),
                ),
                (
                    "signature_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de assinaturas verificadas",
                        verbose_name="Assinaturas",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de visualizações da página",
                        verbose_name="Visualizações",
                    ),
                ),
                (
                    "share_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de compartilhamentos em redes sociais",
                        verbose_name="Compartilhamentos",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de publicação da petição",
                        null=True,
                        verbose_name="Publicado em",
                    ),
                ),
                (
                    "moderation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas internas para moderadores",
                        verbose_name="Notas de moderação",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoria temática da petição",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petitions",
                        to="core.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Usuário que criou a petição",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petitions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Petição",
                "verbose_name_plural": "Petições",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlaggedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email para contato (opcional)",
                        max_length=254,
                        verbose_name="Email do denunciante",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("hate", "Discurso de ódio"),
                            ("misinfo", "Desinformação"),
                            ("offtopic", "Fora do tema"),
                            ("duplicate", "Duplicada"),
                            ("other", "Outro"),
                        ],
                        help_text="Motivo da denúncia",
                        max_length=20,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes adicionais sobre a denúncia",
                        max_length=1000,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("reviewing", "Em análise"),
                            ("approved", "Procedente"),
                            ("dismissed", "Improcedente"),
                        ],
                        default="pending",
                        help_text="Status da análise",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas do moderador sobre a análise",
                        verbose_name="Notas da análise",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Ação realizada pelo moderador",
                        max_length=200,
                        verbose_name="Ação tomada",
                    ),
                ),
                (
                    "ip_address_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 do endereço IP do denunciante",
                        max_length=64,
                        verbose_name="Hash do IP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Analisado em"
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que fez a denúncia (se logado)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Denunciado por",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderador que analisou a denúncia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Analisado por",
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        help_text="Petição denunciada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="petitions.petition",
                        verbose_name="Petição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo denunciado",
                "verbose_name_plural": "Conteúdos denunciados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="petition",
            index=models.Index(
                fields=["status", "is_active", "-created_at"],
                name="petitions_p_status_735b11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="petition",
            index=models.Index(
                fields=["category", "-created_at"],
                name="petitions_p_categor_bb69d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="petition",
            index=models.Index(
                fields=["creator", "-created_at"], name="petitions_p_creator_6bcb00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="petition",
            index=models.Index(
                fields=["-signature_count"], name="petitions_p_signatu_bcc336_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="petition",
            index=models.Index(fields=["uuid"], name="petitions_p_uuid_7268ac_idx"),
        ),
        migrations.AddConstraint(
            model_name="petition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("signature_goal__gte", 10), ("signature_goal__lte", 1000000)
                ),
                name="valid_signature_goal",
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(
                fields=["petition", "status", "-created_at"],
                name="petitions_f_petitio_ee0e8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(
                fields=["status", "-created_at"], name="petitions_f_status_f33472_idx"
            ),
        ),
    ]
