# Generated by Django 5.0.1 on 2026-01-23 04:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moderationlog'),
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Campo de busca full-text (gerado automaticamente)', null=True, verbose_name='Vetor de Busca'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['deadline'], name='petitions_p_deadlin_669475_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='petition_search_idx'),
        ),
    ]
