# Generated by Django 5.0.1 on 2026-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='pdf_file_key',
            field=models.CharField(blank=True, help_text='Chave do arquivo PDF no S3', max_length=500, verbose_name='Chave do arquivo PDF'),
        ),
    ]
