# Generated by Django 5.0.1 on 2026-01-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome da categoria (ex: Saúde, Educação)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigável (gerado automaticamente)",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da categoria",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nome do ícone Bootstrap ou Font Awesome (ex: 'heart', 'book')",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#0066CC",
                        help_text="Cor hexadecimal para exibição (ex: #FF5733)",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição (menor = primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Se desativada, não aparece para novas petições",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["active", "order"], name="core_catego_active_246833_idx"
                    )
                ],
            },
        ),
    ]
