# Generated by Django 5.0.1 on 2026-01-23 04:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('petition_approve', 'Petição Aprovada'), ('petition_reject', 'Petição Rejeitada'), ('petition_archive', 'Petição Arquivada'), ('signature_approve', 'Assinatura Aprovada'), ('signature_reject', 'Assinatura Rejeitada'), ('signature_bulk_approve', 'Assinaturas Aprovadas em Lote'), ('signature_bulk_reject', 'Assinaturas Rejeitadas em Lote'), ('user_ban', 'Usuário Banido'), ('user_unban', 'Usuário Desbanido')], max_length=50, verbose_name='Tipo de Ação')),
                ('content_type', models.CharField(help_text='petition, signature, user', max_length=50, verbose_name='Tipo de Conteúdo')),
                ('object_id', models.CharField(max_length=255, verbose_name='ID do Objeto')),
                ('reason', models.TextField(blank=True, help_text='Razão para a ação de moderação', verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais visíveis apenas para moderadores', verbose_name='Notas Internas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Moderador')),
            ],
            options={
                'verbose_name': 'Log de Moderação',
                'verbose_name_plural': 'Logs de Moderação',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_modera_created_fbef80_idx'), models.Index(fields=['moderator', '-created_at'], name='core_modera_moderat_d8e608_idx'), models.Index(fields=['action_type', '-created_at'], name='core_modera_action__774dc3_idx'), models.Index(fields=['content_type', 'object_id'], name='core_modera_content_a64c84_idx')],
            },
        ),
    ]
