# Generated by Django 5.0.1 on 2026-01-22 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único da assinatura",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Nome completo do signatário",
                        max_length=200,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "cpf_hash",
                    models.CharField(
                        help_text="Hash SHA-256 do CPF (não armazenamos CPF em texto)",
                        max_length=64,
                        verbose_name="Hash do CPF",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email para confirmação",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Cidade do signatário",
                        max_length=100,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        help_text="Estado do signatário",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "signed_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Arquivo PDF assinado digitalmente",
                        null=True,
                        upload_to="signatures/pdfs/",
                        verbose_name="PDF Assinado",
                    ),
                ),
                (
                    "signed_pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL do PDF assinado via Gov.br",
                        max_length=500,
                        verbose_name="URL do PDF assinado",
                    ),
                ),
                (
                    "signed_pdf_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tamanho do arquivo em bytes",
                        null=True,
                        verbose_name="Tamanho do PDF",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("manual_review", "Revisão Manual"),
                        ],
                        default="pending",
                        help_text="Status da verificação automática",
                        max_length=20,
                        verbose_name="Status de verificação",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do processo de verificação",
                        verbose_name="Notas de verificação",
                    ),
                ),
                (
                    "verified_cpf_from_certificate",
                    models.BooleanField(
                        default=False,
                        help_text="Se o CPF foi extraído e validado do certificado digital",
                        verbose_name="CPF verificado do certificado",
                    ),
                ),
                (
                    "certificate_info",
                    models.JSONField(
                        blank=True,
                        help_text="Dados extraídos do certificado digital (JSON)",
                        null=True,
                        verbose_name="Informações do certificado",
                    ),
                ),
                (
                    "display_name_publicly",
                    models.BooleanField(
                        default=False,
                        help_text="Se True, exibe nome completo. Se False, apenas iniciais.",
                        verbose_name="Exibir nome publicamente",
                    ),
                ),
                (
                    "receive_updates",
                    models.BooleanField(
                        default=False,
                        help_text="Aceita receber emails sobre o progresso da petição",
                        verbose_name="Receber atualizações",
                    ),
                ),
                (
                    "ip_address_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 do endereço IP (para auditoria)",
                        max_length=64,
                        verbose_name="Hash do IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Informações do navegador (para detecção de fraude)",
                        max_length=500,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Quando a assinatura foi enviada",
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora extraída do certificado digital",
                        null=True,
                        verbose_name="Assinado em",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando a verificação foi concluída",
                        null=True,
                        verbose_name="Verificado em",
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        help_text="Petição assinada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="petitions.petition",
                        verbose_name="Petição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["petition", "verification_status", "-created_at"],
                        name="signatures__petitio_bcba69_idx",
                    ),
                    models.Index(
                        fields=["verification_status", "-created_at"],
                        name="signatures__verific_906498_idx",
                    ),
                    models.Index(
                        fields=["cpf_hash", "petition"],
                        name="signatures__cpf_has_544097_idx",
                    ),
                    models.Index(fields=["email"], name="signatures__email_2ab480_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="signature",
            constraint=models.UniqueConstraint(
                fields=("petition", "cpf_hash"), name="unique_cpf_per_petition"
            ),
        ),
    ]
