# Generated by Django 5.1.12 on 2026-01-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo pelo qual a assinatura foi rejeitada",
                verbose_name="Motivo da rejeição",
            ),
        ),
    ]
