# Generated by Django 5.1.12 on 2026-01-25 04:02

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0002_signature_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="certificate_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o certificado de custódia foi gerado",
                null=True,
                verbose_name="Certificado Gerado em",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="certificate_issuer",
            field=models.CharField(
                blank=True,
                help_text="Issuer DN do certificado digital",
                max_length=500,
                verbose_name="Emissor do Certificado",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="certificate_serial",
            field=models.CharField(
                blank=True,
                help_text="Número de série do certificado digital",
                max_length=100,
                verbose_name="Número de Série",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="certificate_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject DN do certificado digital",
                max_length=500,
                verbose_name="Assunto do Certificado",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="chain_of_custody",
            field=models.JSONField(
                blank=True,
                help_text="Timeline completa de eventos (JSON)",
                null=True,
                verbose_name="Cadeia de Custódia",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="custody_certificate_pdf",
            field=models.FileField(
                blank=True,
                help_text="Certificado PDF da cadeia de custódia",
                null=True,
                storage=config.storage_backends.MediaStorage(),
                upload_to="signatures/custody_certificates/",
                verbose_name="Certificado de Custódia",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="custody_certificate_url",
            field=models.URLField(
                blank=True,
                help_text="URL do certificado de custódia no S3",
                max_length=500,
                verbose_name="URL do Certificado de Custódia",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="processing_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a verificação terminou",
                null=True,
                verbose_name="Processamento Concluído em",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="processing_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a verificação começou",
                null=True,
                verbose_name="Processamento Iniciado em",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="verification_evidence",
            field=models.JSONField(
                blank=True,
                help_text="Registro completo de todas as etapas de verificação (JSON)",
                null=True,
                verbose_name="Evidências de Verificação",
            ),
        ),
        migrations.AddField(
            model_name="signature",
            name="verification_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash das evidências de verificação",
                max_length=64,
                verbose_name="Hash de Verificação",
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                help_text="Arquivo PDF assinado digitalmente",
                null=True,
                storage=config.storage_backends.MediaStorage(),
                upload_to="signatures/pdfs/",
                verbose_name="PDF Assinado",
            ),
        ),
    ]
